apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-fetcher
  namespace: joke-fetcher
  annotations:
    description: "Deployment for fetching and logging jokes every 5 minutes."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-fetcher
  template:
    metadata:
      labels:
        app: joke-fetcher
    spec:
      containers:
      - name: joke-fetcher
        image: joke-fetcher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
