apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-fetcher
  namespace: joke-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-fetcher
  template:
    metadata:
      labels:
        app: joke-fetcher
    spec:
      containers:
      - name: joke-fetcher
        image: joke-fetcher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
