apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
      instanceProfile: karpenter-node-role
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64", "arm64"]
  limits:
    resources:
      cpu: "4"
      memory: "8Gi"
  ttlSecondsAfterEmpty: 30
